import type { SeedCoach } from '../seedTypes';

/**
 * Coaches, each in his PRIME version.
 * m = CoachModifiers (integers in −5…+12) fed directly to the match engine.
 */
export const COACHES: SeedCoach[] = [
  {
    n: 'Pep Guardiola', nat: 'ESP', prime: '2008-2012', era: '2010s', ovr: 95,
    style: 'Juego de posición: palla, pazienza e superiorità numerica',
    tactic: 'possession',
    m: { possession: 10, passing: 8, pressing: 5, defense: 2, counter: -2, attack: 7, leadManagement: 4, deficitManagement: 5, adaptability: 5, motivation: 5 },
    tags: ['modern', 'champions', 'laliga', 'bundesliga', 'premier'],
  },
  {
    n: 'Alex Ferguson', nat: 'SCO', prime: '1998-2008', era: '2000s', ovr: 95,
    style: 'Ali, velocità e fame infinita: la partita finisce quando lo decide lui',
    tactic: 'direct',
    m: { possession: 2, passing: 4, pressing: 4, defense: 5, counter: 7, attack: 9, leadManagement: 7, deficitManagement: 12, adaptability: 9, motivation: 12 },
    tags: ['legend', 'champions', 'premier'],
  },
  {
    n: 'José Mourinho', nat: 'POR', prime: '2004-2010', era: '2000s', ovr: 93,
    style: 'Blocco compatto, ripartenze letali e il mondo contro di noi',
    tactic: 'counter',
    m: { possession: -3, passing: 0, pressing: 2, defense: 10, counter: 8, attack: 2, leadManagement: 10, deficitManagement: 4, adaptability: 7, motivation: 9 },
    tags: ['legend', 'modern', 'champions', 'premier', 'serie_a', 'laliga'],
  },
  {
    n: 'Carlo Ancelotti', nat: 'ITA', prime: '2003-2007', era: '2000s', ovr: 93,
    style: 'Il sopracciglio calmo: gestione dei campioni ed equilibrio perfetto',
    tactic: 'balanced',
    m: { possession: 4, passing: 6, pressing: 1, defense: 6, counter: 4, attack: 6, leadManagement: 8, deficitManagement: 6, adaptability: 10, motivation: 9 },
    tags: ['legend', 'modern', 'champions', 'serie_a', 'laliga', 'premier', 'bundesliga'],
  },
  {
    n: 'Rinus Michels', nat: 'NED', prime: '1970-1974', era: '70s', ovr: 93,
    style: 'Il Generale del calcio totale: tutti attaccano, tutti difendono',
    tactic: 'total_football',
    m: { possession: 8, passing: 8, pressing: 9, defense: 3, counter: 3, attack: 10, leadManagement: 4, deficitManagement: 5, adaptability: 5, motivation: 8 },
    tags: ['legend', 'champions', 'world_cup', 'laliga'],
  },
  {
    n: 'Johan Cruyff', nat: 'NED', prime: '1990-1994', era: '90s', ovr: 92,
    style: 'Dream Team: rombo, possesso e spettacolo prima del risultato',
    tactic: 'total_football',
    m: { possession: 10, passing: 9, pressing: 5, defense: -3, counter: 1, attack: 11, leadManagement: 1, deficitManagement: 6, adaptability: 2, motivation: 7 },
    tags: ['legend', 'champions', 'laliga'],
  },
  {
    n: 'Arrigo Sacchi', nat: 'ITA', prime: '1987-1991', era: '80s', ovr: 92,
    style: 'Zona, pressing e squadra corta in venticinque metri',
    tactic: 'gegenpress',
    m: { possession: 4, passing: 5, pressing: 9, defense: 8, counter: 3, attack: 6, leadManagement: 5, deficitManagement: 3, adaptability: -2, motivation: 7 },
    tags: ['legend', 'champions', 'serie_a', 'italia'],
  },
  {
    n: 'Jürgen Klopp', nat: 'GER', prime: '2018-2020', era: '2010s', ovr: 92,
    style: 'Heavy metal football: gegenpressing, intensità e cuore',
    tactic: 'gegenpress',
    m: { possession: 2, passing: 4, pressing: 11, defense: 4, counter: 7, attack: 8, leadManagement: 4, deficitManagement: 8, adaptability: 4, motivation: 10 },
    tags: ['modern', 'champions', 'premier', 'bundesliga'],
  },
  {
    n: 'Marcello Lippi', nat: 'ITA', prime: '1994-1998', era: '90s', ovr: 91,
    style: 'Pragmatismo vincente: gruppo solido, carattere e mentalità da grande',
    tactic: 'balanced',
    m: { possession: 2, passing: 4, pressing: 4, defense: 8, counter: 5, attack: 5, leadManagement: 9, deficitManagement: 6, adaptability: 8, motivation: 9 },
    tags: ['legend', 'champions', 'world_cup', 'serie_a', 'italia'],
  },
  {
    n: 'Zinedine Zidane', nat: 'FRA', prime: '2016-2018', era: '2010s', ovr: 91,
    style: 'Gestione delle stelle e nervi saldi nelle notti di Champions',
    tactic: 'balanced',
    m: { possession: 4, passing: 5, pressing: 2, defense: 4, counter: 6, attack: 7, leadManagement: 6, deficitManagement: 8, adaptability: 11, motivation: 11 },
    tags: ['modern', 'champions', 'laliga'],
  },
  {
    n: 'Fabio Capello', nat: 'ITA', prime: '1991-1996', era: '90s', ovr: 90,
    style: 'Disciplina ferrea, difesa di ferro e cinismo nel chiudere le partite',
    tactic: 'balanced',
    m: { possession: 1, passing: 3, pressing: 5, defense: 10, counter: 5, attack: 4, leadManagement: 10, deficitManagement: 3, adaptability: 6, motivation: 7 },
    tags: ['legend', 'champions', 'serie_a', 'laliga'],
  },
  {
    n: 'Giovanni Trapattoni', nat: 'ITA', prime: '1981-1985', era: '80s', ovr: 90,
    style: 'Marcatura a uomo, libero e contropiede: non dire gatto se non ce l\'hai nel sacco',
    tactic: 'catenaccio',
    m: { possession: -3, passing: 1, pressing: 2, defense: 12, counter: 9, attack: 2, leadManagement: 12, deficitManagement: 2, adaptability: 6, motivation: 8 },
    tags: ['legend', 'champions', 'serie_a', 'bundesliga', 'italia'],
  },
  {
    n: 'Jupp Heynckes', nat: 'GER', prime: '2011-2013', era: '2010s', ovr: 90,
    style: 'Il saggio del Triplete: equilibrio totale, pressing e verticalità',
    tactic: 'balanced',
    m: { possession: 6, passing: 6, pressing: 7, defense: 7, counter: 7, attack: 8, leadManagement: 7, deficitManagement: 5, adaptability: 8, motivation: 8 },
    tags: ['legend', 'champions', 'bundesliga', 'laliga'],
  },
  {
    n: 'Diego Simeone', nat: 'ARG', prime: '2013-2016', era: '2010s', ovr: 89,
    style: 'Cholismo: blocco basso, sacrificio e partita dopo partita',
    tactic: 'catenaccio',
    m: { possession: -4, passing: 0, pressing: 8, defense: 11, counter: 8, attack: 1, leadManagement: 11, deficitManagement: 3, adaptability: 3, motivation: 10 },
    tags: ['modern', 'laliga'],
  },
  {
    n: 'Antonio Conte', nat: 'ITA', prime: '2011-2014', era: '2010s', ovr: 89,
    style: 'Tre dietro, esterni a tutta fascia e fame feroce: si vince col sudore',
    tactic: 'direct',
    m: { possession: 1, passing: 5, pressing: 7, defense: 8, counter: 7, attack: 6, leadManagement: 8, deficitManagement: 5, adaptability: 1, motivation: 12 },
    tags: ['modern', 'serie_a', 'premier', 'italia'],
  },
  {
    n: 'Arsène Wenger', nat: 'FRA', prime: '2001-2004', era: '2000s', ovr: 89,
    style: 'Gli Invincibili: tocchi rapidi, tecnica e bellezza in velocità',
    tactic: 'possession',
    m: { possession: 7, passing: 9, pressing: 3, defense: 1, counter: 6, attack: 9, leadManagement: 3, deficitManagement: 5, adaptability: 4, motivation: 7 },
    tags: ['legend', 'premier'],
  },
  {
    n: 'Vicente del Bosque', nat: 'ESP', prime: '2009-2012', era: '2010s', ovr: 89,
    style: 'Tiki-taka tranquillo: controllo, possesso e zero drammi',
    tactic: 'possession',
    m: { possession: 9, passing: 8, pressing: 3, defense: 6, counter: 0, attack: 4, leadManagement: 8, deficitManagement: 2, adaptability: 6, motivation: 7 },
    tags: ['legend', 'champions', 'world_cup', 'laliga'],
  },
  {
    n: 'Louis van Gaal', nat: 'NED', prime: '1993-1996', era: '90s', ovr: 88,
    style: 'Filosofia e sistema: posizioni rigide, possesso e giovani al potere',
    tactic: 'possession',
    m: { possession: 9, passing: 7, pressing: 6, defense: 4, counter: 0, attack: 6, leadManagement: 5, deficitManagement: 3, adaptability: 3, motivation: 5 },
    tags: ['legend', 'champions', 'laliga', 'bundesliga', 'premier'],
  },
  {
    n: 'Thomas Tuchel', nat: 'GER', prime: '2020-2023', era: '2020s', ovr: 87,
    style: 'Camaleonte tattico: difesa a tre, pressing mirato e piani su misura',
    tactic: 'balanced',
    m: { possession: 5, passing: 6, pressing: 7, defense: 8, counter: 5, attack: 5, leadManagement: 7, deficitManagement: 4, adaptability: 10, motivation: 5 },
    tags: ['modern', 'champions', 'premier', 'bundesliga'],
  },
  {
    n: 'Massimiliano Allegri', nat: 'ITA', prime: '2014-2017', era: '2010s', ovr: 87,
    style: 'Corto muso: calma, gestione e vincere 1-0 è un\'arte',
    tactic: 'balanced',
    m: { possession: 1, passing: 4, pressing: 2, defense: 9, counter: 6, attack: 3, leadManagement: 10, deficitManagement: 4, adaptability: 9, motivation: 6 },
    tags: ['modern', 'serie_a'],
  },
  {
    n: 'Hansi Flick', nat: 'GER', prime: '2019-2021', era: '2020s', ovr: 86,
    style: 'Linea altissima, pressing asfissiante e valanga di gol',
    tactic: 'gegenpress',
    m: { possession: 6, passing: 6, pressing: 10, defense: 0, counter: 6, attack: 11, leadManagement: 3, deficitManagement: 6, adaptability: 2, motivation: 8 },
    tags: ['modern', 'champions', 'bundesliga', 'laliga'],
  },
  {
    n: 'Joachim Löw', nat: 'GER', prime: '2012-2016', era: '2010s', ovr: 85,
    style: 'Macchina tedesca moderna: fraseggio, organizzazione e freddezza',
    tactic: 'balanced',
    m: { possession: 6, passing: 7, pressing: 5, defense: 4, counter: 6, attack: 7, leadManagement: 5, deficitManagement: 4, adaptability: 5, motivation: 5 },
    tags: ['legend', 'modern', 'world_cup'],
  },
  {
    n: 'Marcelo Bielsa', nat: 'ARG', prime: '2010-2012', era: '2010s', ovr: 84,
    style: 'El Loco: uomo contro uomo a tutto campo, verticalità e zero compromessi',
    tactic: 'gegenpress',
    m: { possession: 5, passing: 5, pressing: 12, defense: -2, counter: 4, attack: 10, leadManagement: -3, deficitManagement: 7, adaptability: -4, motivation: 9 },
    tags: ['modern', 'laliga', 'premier'],
  },
  {
    n: 'Luciano Spalletti', nat: 'ITA', prime: '2022-2023', era: '2020s', ovr: 84,
    style: 'Calcio relazionale: possesso fluido, rotazioni e mezzali tra le linee',
    tactic: 'possession',
    m: { possession: 8, passing: 8, pressing: 6, defense: 2, counter: 4, attack: 8, leadManagement: 3, deficitManagement: 4, adaptability: 4, motivation: 4 },
    tags: ['modern', 'serie_a', 'italia'],
  },
  {
    n: 'Bob Paisley', nat: 'ENG', prime: '1976-1981', era: '70s', ovr: 91,
    style: 'Il nonno di Anfield: pass and move, umiltà e tre Coppe dei Campioni in pantofole',
    tactic: 'balanced',
    m: { possession: 6, passing: 7, pressing: 5, defense: 7, counter: 5, attack: 7, leadManagement: 8, deficitManagement: 6, adaptability: 7, motivation: 9 },
    tags: ['legend', 'champions'],
  },
  {
    n: 'Brian Clough', nat: 'ENG', prime: '1977-1980', era: '70s', ovr: 90,
    style: 'Old Big \'Ead: palla a terra, carisma smisurato e due Coppe dei Campioni col Forest',
    tactic: 'direct',
    m: { possession: 3, passing: 6, pressing: 4, defense: 7, counter: 7, attack: 6, leadManagement: 8, deficitManagement: 6, adaptability: 5, motivation: 12 },
    tags: ['legend', 'champions', 'cult'],
  },
  {
    n: 'Luis Enrique', nat: 'ESP', prime: '2014-2016', era: '2010s', ovr: 89,
    style: 'MSN a briglia sciolta: verticalità, pressing alto e zero pazienza per i divi',
    tactic: 'possession',
    m: { possession: 8, passing: 7, pressing: 8, defense: 3, counter: 6, attack: 10, leadManagement: 5, deficitManagement: 6, adaptability: 5, motivation: 7 },
    tags: ['modern', 'champions', 'laliga'],
  },
  {
    n: 'Nereo Rocco', nat: 'ITA', prime: '1967-1972', era: '70s', ovr: 88,
    style: 'El Paròn: libero, catenaccio e "ciò, speremo de no" prima di ogni partita',
    tactic: 'catenaccio',
    m: { possession: -3, passing: 1, pressing: 1, defense: 11, counter: 9, attack: 2, leadManagement: 10, deficitManagement: 2, adaptability: 4, motivation: 9 },
    tags: ['legend', 'champions', 'serie_a', 'italia'],
  },
  {
    n: 'Ottmar Hitzfeld', nat: 'GER', prime: '1997-2001', era: '90s', ovr: 88,
    style: 'Il Generale: rotazioni scientifiche e Champions vinte con due club diversi',
    tactic: 'balanced',
    m: { possession: 4, passing: 5, pressing: 5, defense: 8, counter: 6, attack: 5, leadManagement: 9, deficitManagement: 5, adaptability: 8, motivation: 7 },
    tags: ['legend', 'champions', 'bundesliga'],
  },
  {
    n: 'Simone Inzaghi', nat: 'ITA', prime: '2022-2025', era: '2020s', ovr: 86,
    style: 'Tre dietro, braccetti che si sovrappongono e cambi al 60\' col cronometro',
    tactic: 'balanced',
    m: { possession: 5, passing: 7, pressing: 4, defense: 6, counter: 6, attack: 7, leadManagement: 5, deficitManagement: 4, adaptability: 6, motivation: 6 },
    tags: ['modern', 'serie_a', 'champions'],
  },
  {
    n: 'Maurizio Sarri', nat: 'ITA', prime: '2016-2018', era: '2010s', ovr: 83,
    style: 'Sarrismo: tuta, sigaretta e passaggi di prima a un tocco fino allo sfinimento',
    tactic: 'possession',
    m: { possession: 8, passing: 8, pressing: 5, defense: 1, counter: 1, attack: 7, leadManagement: 2, deficitManagement: 3, adaptability: -2, motivation: 5 },
    tags: ['modern', 'serie_a', 'premier', 'cult'],
  },
  {
    n: 'Gian Piero Gasperini', nat: 'ITA', prime: '2019-2024', era: '2020s', ovr: 83,
    style: 'Uomo contro uomo a tutto campo: si corre finché non si vomita, poi si vince l\'Europa League',
    tactic: 'gegenpress',
    m: { possession: 3, passing: 4, pressing: 10, defense: 1, counter: 5, attack: 8, leadManagement: 2, deficitManagement: 6, adaptability: 2, motivation: 7 },
    tags: ['modern', 'serie_a', 'cult'],
  },
  {
    n: 'Claudio Ranieri', nat: 'ITA', prime: '2015-2016', era: '2010s', ovr: 82,
    style: 'Dilly-ding, dilly-dong: 4-4-2 compatto, ripartenze e il miracolo del Leicester',
    tactic: 'counter',
    m: { possession: -3, passing: 1, pressing: 4, defense: 6, counter: 8, attack: 3, leadManagement: 6, deficitManagement: 3, adaptability: 5, motivation: 9 },
    tags: ['legend', 'modern', 'premier', 'serie_a', 'cult'],
  },
  {
    n: 'Walter Mazzarri', nat: 'ITA', prime: '2010-2013', era: '2010s', ovr: 78,
    style: 'Tre dietro, ripartenze a razzo e sempre una colpa da dare al calendario',
    tactic: 'counter',
    m: { possession: -2, passing: 2, pressing: 3, defense: 5, counter: 7, attack: 4, leadManagement: 4, deficitManagement: 3, adaptability: 2, motivation: 5 },
    tags: ['modern', 'serie_a'],
  },
  {
    n: 'Zdeněk Zeman', nat: 'CZE', prime: '1991-1994', era: '90s', ovr: 78,
    style: 'Zemanlandia: 4-3-3, gradoni e segnare un gol in più di quelli che si prendono',
    tactic: 'total_football',
    m: { possession: 3, passing: 4, pressing: 8, defense: -5, counter: 4, attack: 10, leadManagement: -3, deficitManagement: 5, adaptability: -4, motivation: 6 },
    tags: ['legend', 'serie_a', 'cult'],
  },
  {
    n: 'Francesco Guidolin', nat: 'ITA', prime: '2010-2013', era: '2010s', ovr: 77,
    style: 'Il ciclista di Udine: 3-5-1-1, ripartenze e Totò Di Natale in punta',
    tactic: 'counter',
    m: { possession: -1, passing: 3, pressing: 3, defense: 5, counter: 6, attack: 4, leadManagement: 4, deficitManagement: 2, adaptability: 3, motivation: 4 },
    tags: ['modern', 'serie_a'],
  },
  {
    n: 'Carlo Mazzone', nat: 'ITA', prime: '2000-2002', era: '2000s', ovr: 77,
    style: 'Er Sor Magara: sanguigno, paterno e capace di correre sotto la curva avversaria',
    tactic: 'balanced',
    m: { possession: 0, passing: 3, pressing: 2, defense: 5, counter: 5, attack: 3, leadManagement: 5, deficitManagement: 4, adaptability: 3, motivation: 10 },
    tags: ['legend', 'serie_a', 'cult'],
  },
  {
    n: 'Luigi Delneri', nat: 'ITA', prime: '2001-2002', era: '2000s', ovr: 76,
    style: 'Il Chievo dei miracoli: 4-4-2 piatto, ali a tutta e pressing da provinciale terribile',
    tactic: 'direct',
    m: { possession: 0, passing: 2, pressing: 6, defense: 2, counter: 5, attack: 5, leadManagement: 2, deficitManagement: 3, adaptability: 0, motivation: 6 },
    tags: ['legend', 'serie_a'],
  },

  // ───────────────────────────── Bidoni ─────────────────────────────
  {
    n: 'Luigi Maifredi', nat: 'ITA', prime: '1990-1991', era: '90s', ovr: 66,
    style: 'Il calcio champagne che a Torino è diventato spumante sgasato: settimi e fuori dall\'Europa',
    tactic: 'total_football',
    m: { possession: 2, passing: 2, pressing: 3, defense: -3, counter: 0, attack: 3, leadManagement: -3, deficitManagement: 1, adaptability: -2, motivation: 2 },
    tags: ['legend', 'serie_a', 'bidoni', 'cult'],
  },
  {
    n: 'Andrea Stramaccioni', nat: 'ITA', prime: '2012-2013', era: '2010s', ovr: 64,
    style: 'Dalla Primavera alla panchina dell\'Inter: entusiasmo a mille, risultati a picco',
    tactic: 'balanced',
    m: { possession: 1, passing: 1, pressing: 2, defense: -2, counter: 1, attack: 2, leadManagement: -3, deficitManagement: 0, adaptability: -1, motivation: 3 },
    tags: ['modern', 'serie_a', 'bidoni'],
  },
  {
    n: 'Ciro Ferrara', nat: 'ITA', prime: '2009-2010', era: '2000s', ovr: 62,
    style: 'Grande difensore, allenatore meno: Juve travolta e esonero a gennaio',
    tactic: 'balanced',
    m: { possession: 0, passing: 1, pressing: 0, defense: 1, counter: 0, attack: 0, leadManagement: -2, deficitManagement: -3, adaptability: -2, motivation: 2 },
    tags: ['legend', 'serie_a', 'bidoni'],
  },
  {
    n: 'Gian Piero Ventura', nat: 'ITA', prime: '2016-2017', era: '2010s', ovr: 61,
    style: 'Il 4-2-4 contro la Spagna e Insigne in panchina: l\'Italia a casa dal Mondiale',
    tactic: 'balanced',
    m: { possession: 0, passing: 1, pressing: 1, defense: 1, counter: 0, attack: -1, leadManagement: -1, deficitManagement: -5, adaptability: -4, motivation: -3 },
    tags: ['modern', 'italia', 'bidoni', 'cult'],
  },
  {
    n: 'Frank de Boer', nat: 'NED', prime: '2016-2017', era: '2010s', ovr: 60,
    style: 'Possesso olandese in 85 giorni all\'Inter e 77 al Palace: record di velocità, al contrario',
    tactic: 'possession',
    m: { possession: 3, passing: 2, pressing: 0, defense: -3, counter: -2, attack: 0, leadManagement: -2, deficitManagement: -3, adaptability: -4, motivation: -2 },
    tags: ['modern', 'serie_a', 'premier', 'bidoni', 'cult'],
  },
  {
    n: 'Steve McClaren', nat: 'ENG', prime: '2006-2007', era: '2000s', ovr: 57,
    style: 'Il pirla con l\'ombrello: sotto la pioggia di Wembley l\'Inghilterra salta l\'Europeo',
    tactic: 'direct',
    m: { possession: -1, passing: 0, pressing: 1, defense: -2, counter: 1, attack: 0, leadManagement: -4, deficitManagement: -3, adaptability: -3, motivation: -2 },
    tags: ['legend', 'bidoni', 'cult'],
  },
];
